workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      java: 17
      vars:
        GRADLE_OPTS: "-Xmx3072m"
    scripts:
      - name: Build Debug APK (using system gradle)
        script: gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - "amitkunapara06@gmail.com"
